"""add_status_deleted_at_to_all_tables

Revision ID: 5edb3fb7f759
Revises: f6ba7d27bc50
Create Date: 2026-04-10 23:56:58.529795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edb3fb7f759'
down_revision: Union[str, Sequence[str], None] = 'f6ba7d27bc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('appointments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doctors', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('doctors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('doctors', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('medicines', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('medicines', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('medicines', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'status')
    op.drop_column('medicines', 'deleted_at')
    op.drop_column('medicines', 'created_at')
    op.drop_column('medicines', 'status')
    op.drop_column('doctors', 'deleted_at')
    op.drop_column('doctors', 'created_at')
    op.drop_column('doctors', 'status')
    op.drop_column('appointments', 'deleted_at')
    op.drop_column('appointments', 'created_at')
    # ### end Alembic commands ###
